### ISSUE TITLE
Is it possible to get multiple recognition results instead of one?

### ISSUE THREAD

**Issue by zhwa** [facebookresearch/gtn_applications#11]
It seems that in ```model.viterbi(self, outputs)```, only one recognition results will be returned for each sample. Is it possible to return multiple alternates from this decoding method, like beam search? If yes, what would be the recommended decoding algorithm? Will that be time consuming?

Thanks!

**Comment by vineelpratap** [comment]
Hi, 
   We currently don't support multiple hypothesis at the moment. Here is the code pointer for `viterbi` - https://github.com/facebookresearch/gtn/blob/master/gtn/functions/shortest.cpp#L190 if you want to hack things to support...
