### ISSUE TITLE
how to load standardFST input ?

### ISSUE THREAD

**Issue by aheba** [facebookresearch/gtn_applications#12]
Hello @awni ,
I'm wondering if GTN support standard FSA format:
```
  0 1 10 0.1
  0 2 20 0.2
  1 2 30 0.3
  1 3 -1 0.4
  2 3 -1 0.5
  3
```

**Comment by awni** [comment]
We don't currently support this in GTN as the GTN WFST has slightly different constraints than the graphs of OpenFST. You check out our [format](https://gtn.readthedocs.io/en/latest/utils.html#_CPPv47loadTxtRKNSt6stringE), it is not too different and should be an easy conversion. 

Also if this is something you think would be useful to have in the GTN core library, please file a a [feature request](https://github.com/facebookresearch/gtn/issues).
