### ISSUE TITLE
Will ASR application be avaliable in the near future?

### ISSUE THREAD

**Issue by snsun** [facebookresearch/gtn_applications#3]
Hi, it seems the IAM task now is available.  Do you have plans to make the ASR scripts ready in the near future?

**Comment by vineelpratap** [comment]
Hi, yes we'll be making all the recipes available from our paper in the next few weeks.

**Comment by awni** [comment]
The recipes can be found here: https://github.com/facebookresearch/gtn_applications/tree/master/recipes/diff_wfst

Let us know if you have any issues running them. Closing this task for now!
